### ISSUE TITLE
etl-framework available ?

### ISSUE THREAD

**Issue by kiquenet** [MassStreetDataSchool/database-programming#1]
https://massstreetuniversity.com/etl-framework/

**Comment by BobLovesData** [comment]
Is this a dead link? Where is it? I was tired of having a cryptic URL so I gave it it's own URL. You can find it at: http://www.datawarehouseetlframework.com/

**Comment by BobLovesData** [comment]
@kiquenet Before I closed this, I wanted to make sure you saw my comment. I figured you'd get a notification but tagged just in case.

**Comment by kiquenet** [comment]
URL OK : http://www.datawarehouseetlframework.com/
